"""Host-neutral local RPC: compatible v1, strict v2, and an async typed client.

This package is transport-neutral and process-local. ``HarnessRpcHost`` binds
the protocol to the public ``BaseHarness`` surface without creating a second
Tool, Policy, or Session execution path.
"""

from __future__ import annotations

from .codec import (
    SCHEMA_VERSION,
    decode_envelope,
    decode_event,
    decode_request,
    decode_response,
    encode_event,
    encode_request,
    encode_response,
    extract_request_id,
    parse_utc_timestamp,
    to_event_data,
)
from .connection import (
    DEFAULT_INBOUND_EVENT_CAPACITY,
    AsyncTextReader,
    AsyncTextWriter,
    JsonlRpcConnection,
)
from .connection_v2 import JsonlRpcV2Connection
from .codec_v2 import (
    SCHEMA_VERSION_V2,
    decode_v2_envelope,
    decode_v2_event,
    decode_v2_request,
    decode_v2_response,
    encode_v2_event,
    encode_v2_request,
    encode_v2_response,
    extract_v2_request_id,
)
from .client import ConfirmationHandler, EvoPiRpcClient, RpcRunHandle
from .client_types import (
    RpcClientEvent,
    RpcConfirmationAck,
    RpcConfirmationAnswer,
    RpcConfirmationDecision,
    RpcConfirmationEvent,
    RpcConfirmationRecord,
    RpcErrorEvent,
    RpcEventBase,
    RpcEventCursor,
    RpcInteractionEvent,
    RpcInteractionReceipt,
    RpcMessage,
    RpcMessageEvent,
    RpcRunEvent,
    RpcRunResult,
    RpcRuntimeStatus,
    RpcServerInfo,
    RpcSubprocessConfig,
    RpcToolCall,
    RpcToolExecutionEvent,
    RpcTurnEvent,
    RpcUnknownEvent,
)
from .event_stream import (
    DEFAULT_CAPACITY,
    DEFAULT_SUBSCRIBER_QUEUE_CAPACITY,
    EventReplayWindow,
    EventStream,
)
from .harness_host import HarnessRpcHost
from .harness_host_v2 import HarnessRpcV2Host
from .server_v2 import RpcV2Host, RpcV2Server, v2_error_response
from .server import CONFIRMATION_DECISIONS, RpcHost, RpcServer, error_response
from .errors import (
    EventCursorExpiredError,
    EventCursorInvalidError,
    EventPublishAfterCloseError,
    EventStreamClosedError,
    EventStreamError,
    EventSubscriberDroppedError,
    RpcCodecError,
    RpcClientError,
    RpcConnectionClosedError,
    RpcConnectionProtocolError,
    RpcCursorError,
    RpcError,
    RpcEventGapError,
    RpcEventDataError,
    RpcHostError,
    RpcHandshakeError,
    RpcProtocolError,
    RpcRemoteError,
    RpcSubprocessError,
)
from .protocol import RpcEnvelope, RpcErrorInfo, RpcEvent, RpcRequest, RpcResponse
from .protocol_v2 import RpcV2Envelope, RpcV2ErrorInfo, RpcV2Event, RpcV2Request, RpcV2Response

__all__ = [
    "CONFIRMATION_DECISIONS",
    "DEFAULT_CAPACITY",
    "DEFAULT_INBOUND_EVENT_CAPACITY",
    "DEFAULT_SUBSCRIBER_QUEUE_CAPACITY",
    "EventStream",
    "EventReplayWindow",
    "HarnessRpcHost",
    "HarnessRpcV2Host",
    "RpcHost",
    "RpcServer",
    "SCHEMA_VERSION",
    "SCHEMA_VERSION_V2",
    "AsyncTextReader",
    "AsyncTextWriter",
    "JsonlRpcConnection",
    "JsonlRpcV2Connection",
    "ConfirmationHandler",
    "EvoPiRpcClient",
    "RpcRunHandle",
    "error_response",
    "extract_request_id",
    "EventCursorExpiredError",
    "EventCursorInvalidError",
    "EventPublishAfterCloseError",
    "EventStreamClosedError",
    "EventStreamError",
    "EventSubscriberDroppedError",
    "RpcCodecError",
    "RpcClientError",
    "RpcConnectionClosedError",
    "RpcConnectionProtocolError",
    "RpcCursorError",
    "RpcEnvelope",
    "RpcError",
    "RpcEventGapError",
    "RpcErrorInfo",
    "RpcEvent",
    "RpcEventDataError",
    "RpcHostError",
    "RpcHandshakeError",
    "RpcProtocolError",
    "RpcRemoteError",
    "RpcRequest",
    "RpcResponse",
    "RpcSubprocessError",
    "RpcClientEvent",
    "RpcConfirmationAck",
    "RpcConfirmationAnswer",
    "RpcConfirmationDecision",
    "RpcConfirmationEvent",
    "RpcConfirmationRecord",
    "RpcErrorEvent",
    "RpcEventBase",
    "RpcEventCursor",
    "RpcInteractionEvent",
    "RpcInteractionReceipt",
    "RpcMessage",
    "RpcMessageEvent",
    "RpcRunEvent",
    "RpcRunResult",
    "RpcRuntimeStatus",
    "RpcServerInfo",
    "RpcSubprocessConfig",
    "RpcToolCall",
    "RpcToolExecutionEvent",
    "RpcTurnEvent",
    "RpcUnknownEvent",
    "RpcV2Envelope",
    "RpcV2ErrorInfo",
    "RpcV2Event",
    "RpcV2Host",
    "RpcV2Request",
    "RpcV2Response",
    "RpcV2Server",
    "v2_error_response",
    "decode_envelope",
    "decode_v2_envelope",
    "decode_v2_event",
    "decode_v2_request",
    "decode_v2_response",
    "decode_event",
    "decode_request",
    "decode_response",
    "encode_event",
    "encode_request",
    "encode_response",
    "encode_v2_event",
    "encode_v2_request",
    "encode_v2_response",
    "extract_v2_request_id",
    "parse_utc_timestamp",
    "to_event_data",
]
